### ISSUE TITLE
Is there a way to change or make the .well-known folder location configurable?

### ISSUE THREAD

**Issue by modemgeek** [shibayan/appservice-acmebot#105]
We were using a webapp extension that did the same thing.  However it's currently broken.  I'm testing this out but I notice it creates the challenge file at /site/.well-known.  For us this path isnt accessible via http.  The path we had before and works is /site/wwwroot/.well-known.  I want to change it to use this path.

**Comment by shibayan** [comment]
If you put the folder under wwwroot, it may be deleted during deployment or readonly. It cannot be changed.
Consider https://github.com/shibayan/keyvault-acmebot if you need to be flexible.

**Comment by modemgeek** [comment]
thank you.  however the key vault version requires you to use Azure DNS, does it not?  we host 100s of websites with unique hostnames on each of our webapps.  We have about 1000 sites that we secure.  None of these use DNS and we don't control DNS for all our customers.
