### ISSUE TITLE
500 Error when issuing new cert

### ISSUE THREAD

**Issue by jonlarson13** [shibayan/appservice-acmebot#108]
hello - 

I am getting a 500 error when I try to issue a new cert. 

It looks like it's failing at: 

`Exception` while executing function: AddCertificate Orchestrator function 'AddCertificate' failed: The activity function 'Dns01Precondition' failed: "Azure DNS zone "<my domain name>" is not found". See the function execution logs for additional details. 

I have the DNS zone for this domain in Azure, however it's in a different resource group from the webapp. 

Do I need to apply more permissions to the resource group that the DNS zone is in?

Thanks!

**Comment by jonlarson13** [comment]
Oh, I see.. it says for Linux apps you DO need to apply more permissions. I should've re-read first!

**Comment by jonlarson13** [comment]
Yep, that fixed it. All good!

**Comment by unstephenk** [comment]
What are the additional permissions?
