### ISSUE TITLE
AddCertificate error

### ISSUE THREAD

**Issue by Immugio** [shibayan/appservice-acmebot#109]
Hello shibayan,

I'm trying to set this up but getting this error. Would you be able to help?

Orchestrator function 'AddCertificate' failed: The activity function 'UpdateCertificate' failed: "Failed to deserialize exception from TaskActivity: {"$type":"Microsoft.Azure.Management.WebSites.Models.DefaultErrorResponseException, Microsoft.Azure.Management.Websites","Request":{"$type":"Microsoft.Rest.HttpRequestMessageWrapper, Microsoft.Rest.ClientRuntime","Method":{"$type":"System.Net.Http.HttpMethod, System.Net.Http","Method":"PUT"},"RequestUri":"https://management.azure.com/subscriptions/70063eb6-ed26-4167-90be-95c2cb95034e/resourceGroups/Planner/providers/Microsoft.Web/certificates/gardenroomplanner.com-F8884E5C752F58A36B0F0E99F178C23AABACE1EB?api-version=2018-11-01","Properties":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib"},"Content":"{\r\n  \"properties\": {\r\n    \"pfxBlob\": 
--Edited--
",\r\n    \"password\": \"",\r\n    \"serverFarmId\": \"/subscriptions/70063eb6-ed26-4167-90be-95c2cb95034e/resourceGroups/Default/providers/Microsoft.Web/serverfarms/immu_plan\"\r\n  },\r\n  \"location\": \"West Europe\"\r\n}","Headers":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Collections.Generic.IEnumerable`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib","x-ms-client-request-id":["645f3bc6-1456-416e-8e6a-8029afbc818b"],"Accept-Language":["en-US"],"Authorization":[
--Edited--
],"User-Agent":["FxVersion/4.6.28008.02","OSName/Windows","OSVersion/Microsoft.Windows.10.0.14393.","Microsoft.Azure.Management.WebSites.WebSiteManagementClient/2.2.0"],"Request-Context":["appId=cid-v1:2c55cbc4-b765-433a-ba4e-f1421a1492f7"],"traceparent":["00-b80b1875a0a6a64f818598376c9acebb-91087dfe69759047-00"],"Request-Id":["|b80b1875a0a6a64f818598376c9acebb.91087dfe69759047."],"Content-Type":["application/json; charset=utf-8"],"Content-Length":["4191"]}},"Response":{"$type":"Microsoft.Rest.HttpResponseMessageWrapper, Microsoft.Rest.ClientRuntime","StatusCode":403,"ReasonPhrase":"Forbidden","Content":"{\"error\":{\"code\":\"LinkedAuthorizationFailed\",\"message\":\"The client 'e1ee2f08-14fd-4bdc-adda-aaf51ba96256' with object id 'e1ee2f08-14fd-4bdc-adda-aaf51ba96256' has permission to perform action 'Microsoft.Web/certificates/write' on scope '/subscriptions/70063eb6-ed26-4167-90be-95c2cb95034e/resourceGroups/Planner/providers/Microsoft.Web/certificates/gardenroomplanner.com-F8884E5C752F58A36B0F0E99F178C23AABACE1EB'; however, it does not have permission to perform action 'write' on the linked scope(s) '/subscriptions/70063eb6-ed26-4167-90be-95c2cb95034e/resourceGroups/Default/providers/Microsoft.Web/serverfarms/immu_plan' or the linked scope(s) are invalid.\"}}","Headers":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Collections.Generic.IEnumerable`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib","Cache-Control":["no-cache"],"Pragma":["no-cache"],"x-ms-failure-cause":["gateway"],"x-ms-request-id":["26df6ce4-45cd-41d8-a429-2ffad8f12eb7"],"x-ms-correlation-request-id":["26df6ce4-45cd-41d8-a429-2ffad8f12eb7"],"x-ms-routing-request-id":["WESTUS:20191101T110439Z:26df6ce4-45cd-41d8-a429-2ffad8f12eb7"],"Strict-Transport-Security":["max-age=31536000; includeSubDomains"],"X-Content-Type-Options":["nosniff"],"Date":["Fri, 01 Nov 2019 11:04:38 GMT"],"Connection":["close"],"Content-Type":["application/json; charset=utf-8"],"Expires":["-1"],"Content-Length":["662"]}},"Body":{"$type":"Microsoft.Azure.Management.WebSites.Models.DefaultErrorResponse, Microsoft.Azure.Management.Websites","error":{"$type":"Microsoft.Azure.Management.WebSites.Models.DefaultErrorResponseError, Microsoft.Azure.Management.Websites","code":"LinkedAuthorizationFailed","message":"The client 'e1ee2f08-14fd-4bdc-adda-aaf51ba96256' with object id 'e1ee2f08-14fd-4bdc-adda-aaf51ba96256' has permission to perform action 'Microsoft.Web/certificates/write' on scope '/subscriptions/70063eb6-ed26-4167-90be-95c2cb95034e/resourceGroups/Planner/providers/Microsoft.Web/certificates/gardenroomplanner.com-F8884E5C752F58A36B0F0E99F178C23AABACE1EB'; however, it does not have permission to perform action 'write' on the linked scope(s) '/subscriptions/70063eb6-ed26-4167-90be-95c2cb95034e/resourceGroups/Default/providers/Microsoft.Web/serverfarms/immu_plan' or the linked scope(s) are invalid.","target":null,"details":null,"innererror":null}},"Message":"Operation returned an invalid status code 'Forbidden'","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib"},"InnerException":null,"StackTrace":"   at Microsoft.Azure.Management.WebSites.CertificatesOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String name, Certificate certificateEnvelope, Dictionary`2 customHeaders, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Management.WebSites.CertificatesOperationsExtensions.CreateOrUpdateAsync(ICertificatesOperations operations, String resourceGroupName, String name, Certificate certificateEnvelope, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\VoidTaskMethodInvoker.cs:line 20\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs:line 52\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 585\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 532\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 468\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 278","HelpLink":null,"Source":"Microsoft.Azure.Management.Websites","HResult":-2146233088}". See the function execution logs for additional details.

**Comment by shibayan** [comment]
`403 Forbidden` is returned. Check the IAM (RBAC) setting after read README.
