### ISSUE TITLE
Issue: adding /well-known path mapping breaks web application

### ISSUE THREAD

**Issue by hahn-kev** [shibayan/appservice-acmebot#110]
I'm running into a problem because whenever the SSL Cert renews a path mapping is added which then breaks my website. My application supports open-id and so serves requests from hostname/.well-known however when my certificate renews a path mapping is added and breaks requests to that path.

It looks like you're configuring the path mapping [here](https://github.com/shibayan/appservice-acmebot/blob/master/AppService.Acmebot/SharedFunctions.cs#L114), is there any way you could clean up that path mapping once the renewal process is finished? Maybe by deleting the path mapping automatically? I saw previously that you recommended using the keyvault bot but I'm not using Azure DNS (only a single domain in azure) so that seems like overkill.

**Comment by shibayan** [comment]
It seems a good idea to clean up the `.well-known` configuration after issuing the certificate.
However, while the certificate is issued, You cannot access `.well-known`. Is this acceptable?

**Comment by hahn-kev** [comment]
Yeah I think that's acceptable. It's not configured for very long and it only happens once every couple of months so I think it's ok.

**Comment by shibayan** [comment]
OK, I will try to implement virtual application cleanup.

**Comment by VaclavElias** [comment]
I also had one application asking to place file here /.well-known/brave-rewards-verification.txt but it didn't work till I realised that the path was changed so I placed it to the folder created by appservice-acmebot. 

Also, you might consider trying this as it might work for some of us https://feedback.azure.com/forums/169385-web-apps/suggestions/36950533-add-support-for-free-tls-ssl-certificates

**Comment by hahn-kev** [comment]
@VaclavElias that's great! Thanks for sharing that!
