### ISSUE TITLE
Add Certificate - This message is too long to display here. Please visit the link to read the content.

### ISSUE THREAD

**Issue by jamescregg** [shibayan/appservice-acmebot#120]
I am trying to add a certificate but am getting the error above. I have checked the detailed logs from D:\home\LogFiles\Application\Functions\function\AddCertificate, but cannot find any clear reason why. 

I thought it might be related to limits. I have removed D:\home\.acme with the same results. I previously got the message that too many certs had been applied but I am no longer getting this error after leaving it for seven days.

**Comment by shibayan** [comment]
That's not an error. Look for it in Application Insights.

**Comment by jamescregg** [comment]
Sorry shibayan, forgot to paste the error. Please see below. 

Exception while executing function: RenewSiteCertificates Orchestrator function 'RenewSiteCertificates' failed: The activity function 'UpdateCertificate' failed: "Failed to deserialize exception from TaskActivity: {"$type":"Microsoft.Azure.Management.WebSites.Models.DefaultErrorResponseException, Microsoft.Azure.Management.Websites","Request":{"$type":"Microsoft.Rest.HttpRequestMessageWrapper, Microsoft.Rest.ClientRuntime","Method":{"$type":"System.Net.Http.HttpMethod, System.Net.Http","Method":"PUT"},"RequestUri":"https://management.azure.com/subscriptions/012345-12345-12345-12345/resourceGroups/xxx/providers/Microsoft.Web/certificates/audisouthdublin.ie-FFA53E6DFCD87832998A79EA7515419BB02F57F1?api-version=2018-11-01","Properties":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Private.CoreLib"},"Content":"{\r\n  \"properties\": {\r\n    \"pfxBlob\": \"MIILgAIBAzCCC0AGCSqGSIb3DQEHAaCCCzEEggstMIILKTCCAW0GCSqGSIb3DQEHAaCCAV4EggFaMIIBVjCCAVIGCyqGSIb3DQEMCgECoIHMMIHJMBwGCiqGSIb3DQEMAQMwDgQI29TiQ05OnLACAgfQBIGoIN0hfgBiR4ox/RB1zuqv4mkS+OqE2sTfjGNNiXnrOtqcgh+MByEYvXDqPy5+/8fTrq/z3PXk6ALWCHrkc8cRYeKozm3HEHTxJwDHAF6HPTgk7ga6JwXecHCElIaHkl9b3E1KwA4vj9OwWn+D5tQ+VCqCjEXl8u7cJpcv9+alznS5BRRA4F3n9e0l4Zdf82cgSaDaxNsZr/4VTmr4zKfv51t0VRU5dlcNMXQwEwYJKoZIhvcNAQkVMQYEBAEAAAAwXQYJKwYBBAGCNxEBMVAeTgBNAGkAYwByAG8AcwBvAGYAdAAgAFMAbwBmAHQAdwBhAHIAZQAgAEsAZQB5ACAAUwB0AG8AcgBhAGcAZQAgAFAAcgBvAHYAaQBkAGUAcjCCCbQGCSqGSIb3DQEHAaCCCaUEggmhMIIJnTCCBMEGCyqGSIb3DQEMCgEDoIIErjCCBKoGCiqGSIb3DQEJFgGgggSaBIIEljCCBJIwggN6oAMCAQICEAoBQUIAAAFThXNqC4XspwgwDQYJKoZIhvcNAQELBQAwPzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQDEw5EU1QgUm9vdCBDQSBYMzAeFw0xNjAzMTcxNjQwNDZaFw0yMTAzMTcxNjQwNDZaMEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQDExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJzTDPBa5S5Ht3JdN4OzaGMw6tc1Jhkl4b2+NfFwki+3uEtBBaupnjUIWOyxKsRohwuj43Xk5vOnYnG6eYFgH9eRmp/z0HhncchpDpWRz/7mmelgPEjMfspNdxIknUcbWuu57B43ABycrHunBerOSuu9QeU2mLnL/W08lmjfIypCkAyGdGfIf6WauFJhFBM/ZemCh8vb+g5W9oaJ84U/l4avsNwa72sNlRZ9xCugZbKZBDZ1gGusSvMbkEl4L6KWTyogJSkExnTA0DHNjzE4lRa6qDO4Q/GxH8Mwf6J5MRM9LTb44/zyM2q5OTHFr8SNDR1kFjOq+oQpttQLwNh9w5MCAwEAAaOCAX0wggF5MBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMH8GCCsGAQUFBwEBBHMwcTAyBggrBgEFBQcwAYYmaHR0cDovL2lzcmcudHJ1c3RpZC5vY3NwLmlkZW50cnVzdC5jb20wOwYIKwYBBQUHMAKGL2h0dHA6Ly9hcHBzLmlkZW50cnVzdC5jb20vcm9vdHMvZHN0cm9vdGNheDMucDdjMB8GA1UdIwQYMBaAFMSnsaR7LHH62+FLkHX/xBVghYkQMFQGA1UdIARNMEswCAYGZ4EMAQIBMD8GCysGAQQBgt8TAQEBMDAwLgYIKwYBBQUHAgEWImh0dHA6Ly9jcHMucm9vdC14MS5sZXRzZW5jcnlwdC5vcmcwPAYDVR0fBDUwMzAxoC+gLYYraHR0cDovL2NybC5pZGVudHJ1c3QuY29tL0RTVFJPT1RDQVgzQ1JMLmNybDAdBgNVHQ4EFgQUqEpqYwR93brm0Tm3pkVl7/Oo7KEwDQYJKoZIhvcNAQELBQADggEBAN0z1xHzY1g43RgV+wlVvnZWuXBIpWlHJ3vCJAiS8VofShIpNyR0URxiaLjNlXBn5fekvE4oUc2b6K6HnerYulqhAZrc8N1qHWrYPlcjnqYeBGKa/9cFyrcfP8AKSLyUsLZlYuDBVOWjKq0gxOnmu9zI9rXDMqOYzHeo5nllByvLKP46FlKBzlIMLl+D6NUGM/t3bM5A6jKeH5JcQcF0bFtdCl8zzE2frDjwL3ssYp3Zo5FvJRsvkLEZRj32fhumeoe5o3ptGPolpZGHFeDyFi9YsAYvLGgmxkuYzdqfDPl/kO1DShJETm9zeijqpKpue0x9h93gyQJEp4evwzRbtEIxADCCBNQGCyqGSIb3DQEMCgEDoIIErDCCBKgGCiqGSIb3DQEJFgGgggSYBIIElDCCBJAwggN4oAMCAQICEgOfDjcTBovFbtmzP5lzzob6BDANBgkqhkiG9w0BAQsFADBKMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3MgRW5jcnlwdDEjMCEGA1UEAxMaTGV0J3MgRW5jcnlwdCBBdXRob3JpdHkgWDMwHhcNMjAwMTE1MDc1NTM0WhcNMjAwNDE0MDc1NTM0WjAdMRswGQYDVQQDExJhdWRpc291dGhkdWJsaW4uaWUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAStmZXg8/QDp8S+XVSk8Qfd/TNGzAljehVzQH+OT/wuKjUAHHB5ByvwZfiQKerfOx/FFggTdgd/pKnzEh4b+vsgo4ICZjCCAmIwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQgARvTwcXzSZJo9679cMNveBmk4DAfBgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggrBgEFBQcBAQRjMGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlwdC5vcmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5jcnlwdC5vcmcvMB0GA1UdEQQWMBSCEmF1ZGlzb3V0aGR1Ymxpbi5pZTBMBgNVHSAERTBDMAgGBmeBDAECATA3BgsrBgEEAYLfEwEBATAoMCYGCCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCCAQMGCisGAQQB1nkCBAIEgfQEgfEA7wB2AF6nc/nfVsDntTZIfdBJ4DJ6kZoMhKESEoQYdZaBcUVYAAABb6hqRVcAAAQDAEcwRQIgULIHcqnFWikA82shClP5UXUjsWQRcn5mQo9xcC52fPoCIQCJIgnIYEgSKKNTnjK6RjfJvyfhJIMXA2SUFxNHfcbyLgB1AAe3XBvlfWj/8bDGHSMVx7rmV3xXlLdq7rxhOhpp06IcAAABb6hqRXcAAAQDAEYwRAIgcUGg2R67BTF7soncsCsrhsw3ZJP6IILbA/0o2pZes8gCIGf8n/jXQhIZEXpcKJB1ve0T+t7tFwiLL4dFwuOsP50OMA0GCSqGSIb3DQEBCwUAA4IBAQAtzbKPzAgnPcWEqw90ljVHbWkV2uyvwKBUYFR/GRf36iDlPNk553tMVJp1L2Or1QCqATSPs7vT5j06Eokuu1tcdPiVAAxcoYXZMPEIWcs2DL/q0t3WGGpMwlH/6X55ED5bV5k/HcBdmEeYUkO7Wn8Hv4y+EFqm21sM91ztYVpEb2Gac8m1Rrqzy02HsKTeAxKJNuw0EULWx2kRhayLKyKdGoYVwWsun2b5OcriftStyVSLrofbPp+JIsn0YhqWtcBvNtCNjTFCBDXfaynPwE3PZIVZja3fMOPuiCMA3r8Wkt4Otck64PlfrJ2nAunIU7bwUWthfr7S92inbdQaeFpRMRUwEwYJKoZIhvcNAQkVMQYEBAEAAAAwNzAfMAcGBSsOAwIaBBRM9Fw/lIu+xAyk0uuyY0fPUOj9GAQUSYwpwg6sas+YhgHX5RGlqYedvkM=\",\r\n    \"password\": \"P@ssw0rd\",\r\n    \"serverFarmId\": \"/subscriptions/012345-12345-12345-12345/resourceGroups/xxx/providers/Microsoft.Web/serverfarms/xxx\"\r\n  },\r\n  \"location\": \"North Europe\"\r\n}","Headers":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Collections.Generic.IEnumerable`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib","x-ms-client-request-id":["ca0a7648-df67-4d5f-a92d-a5ade6db76d3"],"Accept-Language":["en-US"],"Authorization":["Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InBpVmxsb1FEU01LeGgxbTJ5Z3FHU1ZkZ0ZwQSIsImtpZCI6InBpVmxsb1FEU01LeGgxbTJ5Z3FHU1ZkZ0ZwQSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tLyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzhjYzRlY2U1LWRmZjMtNDgyMy04YmJlLTUxYmYzOWNkODM5ZC8iLCJpYXQiOjE1NzkwNjc3MDAsIm5iZiI6MTU3OTA2NzcwMCwiZXhwIjoxNTc5MDk2ODAwLCJhaW8iOiI0Mk5nWU9CSUNWRzZiQzlueU1QMTlGbTRnYkEwQUE9PSIsImFwcGlkIjoiZjA0YTk0NTgtOWE4Zi00NDMwLWJhMTUtYjdhMTA5OTFjMjJkIiwiYXBwaWRhY3IiOiIyIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvOGNjNGVjZTUtZGZmMy00ODIzLThiYmUtNTFiZjM5Y2Q4MzlkLyIsIm9pZCI6IjQ5Y2QzMTU1LTEwNDItNDI2Yi1hNDE1LTkwNGFlOGQ4MGM2MCIsInN1YiI6IjQ5Y2QzMTU1LTEwNDItNDI2Yi1hNDE1LTkwNGFlOGQ4MGM2MCIsInRpZCI6IjhjYzRlY2U1LWRmZjMtNDgyMy04YmJlLTUxYmYzOWNkODM5ZCIsInV0aSI6IldZQUVkeGViNEVTdzBUWXlzV1hYQUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfbWlyaWQiOiIvc3Vic2NyaXB0aW9ucy83OTZiYWI0Zi01NzRiLTQ2OTUtODdmMy1mZDlkYTljYzQ2ZDMvcmVzb3VyY2Vncm91cHMvTEtSU1dlYlBST0QvcHJvdmlkZXJzL01pY3Jvc29mdC5XZWIvc2l0ZXMvTGtzV2ViUHJkQ2VydE1nbXRGbkFwcDAxIn0.AjysNN8x1Oe8bohmLeASJOAJJdTvn5LL67KsawqZNRL3FXjHPuQr-puiwvYNf-tDNluEQyo6T__hmULTzQPMlt2u2wI_jRUZs2DIWTJ-fq4hRubN528EEgRStZI8Cgexu6v283Hf--YNAeQYBcSHTGstoi7pIb5RIiwoJUBev7PaNmvWT_2zQjyTx-eNNAsuLNtHae0myhD5N7E4whRsxMFmiri4iTitLXM7gz_wIZYuZxZG5samSeHQVAQ46crnzgsf727v4k5onlZcnocBRgJu1Acx0UtKGYG6xJuxYSigvtF9uJ6bgeGaCD2G8n-CctI943y7c9e8tfBlIbLI5A"],"User-Agent":["FxVersion/4.6.28207.03","OSName/Windows","OSVersion/Microsoft.Windows.10.0.14393.","Microsoft.Azure.Management.WebSites.WebSiteManagementClient/2.1.0"],"Request-Context":["appId=cid-v1:1ad66f4c-885e-4234-8ec3-3304a9cd1462"],"traceparent":["00-094712daa73e5045af840f75213c21f5-9c50244bf495db4f-00"],"Request-Id":["|094712daa73e5045af840f75213c21f5.9c50244bf495db4f."],"Content-Type":["application/json; charset=utf-8"],"Content-Length":["4200"]}},"Response":{"$type":"Microsoft.Rest.HttpResponseMessageWrapper, Microsoft.Rest.ClientRuntime","StatusCode":500,"ReasonPhrase":"Internal Server Error","Content":"{\"Message\":\"An error has occurred.\"}","Headers":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Collections.Generic.IEnumerable`1[[System.String, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib","Cache-Control":["no-cache"],"Pragma":["no-cache"],"Strict-Transport-Security":["max-age=31536000; includeSubDomains"],"Server":["Microsoft-IIS/10.0"],"X-AspNet-Version":["4.0.30319"],"X-Powered-By":["ASP.NET"],"x-ms-failure-cause":["service"],"x-ms-ratelimit-remaining-subscription-writes":["1197"],"x-ms-request-id":["befc6df6-14d0-4a77-8885-d3cd4472de6d"],"x-ms-correlation-request-id":["befc6df6-14d0-4a77-8885-d3cd4472de6d"],"x-ms-routing-request-id":["NORTHEUROPE:20200115T085556Z:befc6df6-14d0-4a77-8885-d3cd4472de6d"],"X-Content-Type-Options":["nosniff"],"Date":["Wed, 15 Jan 2020 08:55:56 GMT"],"Connection":["close"],"Content-Length":["36"],"Content-Type":["application/json; charset=utf-8"],"Expires":["-1"]}},"Body":{"$type":"Microsoft.Azure.Management.WebSites.Models.DefaultErrorResponse, Microsoft.Azure.Management.Websites","error":null},"Message":"Operation returned an invalid status code 'InternalServerError'","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib"},"InnerException":null,"StackTrace":"   at Microsoft.Azure.Management.WebSites.CertificatesOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String name, Certificate certificateEnvelope, Dictionary`2 customHeaders, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Management.WebSites.CertificatesOperationsExtensions.CreateOrUpdateAsync(ICertificatesOperations operations, String resourceGroupName, String name, Certificate certificateEnvelope, CancellationToken cancellationToken)\r\n   at AzureAppService.LetsEncrypt.SharedFunctions.UpdateCertificate(DurableActivityContext context, ILogger log) in d:\\Sources\\Lookers\\letsencryptmgmtfnapp\\AzureAppService.LetsEncrypt\\SharedFunctions.cs:line 400\r\n   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\VoidTaskMethodInvoker.cs:line 20\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs:line 52\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 585\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 532\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 468\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 278","HelpLink":null,"Source":"Microsoft.Azure.Management.Websites","HResult":-2146233088}". See the function execution logs for additional details.

**Comment by jamescregg** [comment]
@shibayan Sorry, I saw a previous thread which helped. Thanks
