### ISSUE TITLE
Review current certificates

### ISSUE THREAD

**Issue by Immugio** [shibayan/appservice-acmebot#124]
Hello @shibayan, thanks for this awesome software! Is there a way to display the list of certificates that are being maintained?

**Comment by shibayan** [comment]
A list of issued certificates can be viewed from the Azure portal. There are no plans to add a list screen for this app.

**Comment by Immugio** [comment]
Thanks, would you be able to point to how to view them?

**Comment by shibayan** [comment]
You can check from `TLS/SSL settings` in App Service settings.
https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate

**Comment by Immugio** [comment]
thanks!
