### ISSUE TITLE
Support for Storage and Static Websites

### ISSUE THREAD

**Issue by stefandevo** [shibayan/appservice-acmebot#125]
First, thank you very much for this, it is working great and very useful!!

Would it be possible to extend this that it can support SSL certificates for static website hosting in Azure Storage Containers? 
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website

That would be awesome!

**Comment by shibayan** [comment]
Azure Storage does not support custom HTTPS, so you need to have a CDN at the front.

Azure CDN can import certificates from Key Vault, so the Key Vault version should work.
https://github.com/shibayan/keyvault-acmebot

However, the certificate is not automatically uploaded to the CDN, so an additional solution is required.
