### ISSUE TITLE
Where does one load this for Container App Services?

### ISSUE THREAD

**Issue by JohnGalt1717** [shibayan/appservice-acmebot#126]
The documentation doesn't seem to be clear (Or I'm not reading it correctly). 

How does one load this given that extensions are disabled for App Services for containers?  I undersatnd it requires dns in that case, but I can't figure out how to a. load it, and b. get to the management page.

Thanks!

**Comment by shibayan** [comment]
When using with Container, it is necessary to delegate the domain to Azure DNS.

All you need to do is assign a domain to App Service using the Azure DNS zone and configure IAM correctly.
