### ISSUE TITLE
DNS zone search process is wrong.

### ISSUE THREAD

**Issue by shibayan** [shibayan/appservice-acmebot#130]
Original post kamil-mrzyglod
>Hey, so the setup is as follows:
>
>front-end app(web)
>back-end app(api)
>Both have custom domains configured. Both are hosted with separate Web Apps. While requesting for a certificate, custom domains are correctly discovered, however using them to obtain a cert results in "Cannot find Azure DNS Zone". In the logs I saw it searched for web.* and api.* DNS Zones, not the main domain.

#129

**Comment by kamil-mrzyglod** [comment]
Hey @shibayan, do you need more information regarding that issue? I can try to search my logs for additional details.

**Comment by shibayan** [comment]
The process related to DNS has been refined, so it may be fixed.
In my test environment, it worked without having to create a DNS zone for each subdomain. Please let me know if you have anything.

**Comment by kamil-mrzyglod** [comment]
@shibayan Right now I cannot confirm that as that issue affected my production environment. If I have any more information, I'll let you know.

**Comment by shibayan** [comment]
Thank you for confirmation. Please let me know if you have any problems.

**Comment by sphen13** [comment]
Just testing this out for the first time today and I am getting the same behavior. I moved the main domain to azure dns but I get the error in the function stating:
```"Azure DNS zone "report.*" is not found"```

I will attempt to create a zone for the subdomain next to see if it resolves.

**Comment by sphen13** [comment]
well somehow it is working - nevermind. i updated to use a subdomain that i specifically created a zone for in azure, tested and it worked. Then when i went back to test the subdomain that was part of a parent azure zone that previously failed, it worked. ¯\_(ツ)_/¯
