### ISSUE TITLE
Refinement for Step 3 of Getting Started

### ISSUE THREAD

**Issue by justSteve** [shibayan/appservice-acmebot#134]
At 'Enable App Service Authentication (EasyAuth) with AAD' the target is unclear. The breadcrumbs of your screen shot makes it look as though you've chosen the app service via the resource group. I did the same but couldn't see the 'Authentication / Authorization' link.

I was stumped until I noticed the '**Platform features**' tab. Suggest inserting a screen cap or at least an adjustment to the text along the lines of ... _after navigating to the AppService blade look for the **Platform features** tab._

**Comment by shibayan** [comment]
The function portal update removes the blade called `Platform features` and closes this issue.
I will continue to improve the documentation at #135
