### ISSUE TITLE
How does domain validation work?

### ISSUE THREAD

**Issue by mattwoberts** [shibayan/appservice-acmebot#137]
Hi,

I'm currently using the Lets Encrypt site extension to manage my certificates. I am looking at this solution now (since i was directed here from Let's Encrypt), and I'm wondering how the domain validation works?

For the site extension, a file is either placed in the .well-known folder on your app service (and you need to ensure that this can be reached by the validation process), or else you can configure it to be stored in blob storage, and then you have options for redirecting to this blob storage file.

Am I right in thinking that if you want the flexibility that was previously handled with blob storage, I need to look at the azure key vault options?

Thanks :)

**Comment by shibayan** [comment]
In the case of Windows App Service, a `.well-known` directory is created at runtime using the virtual application function. No DNS is needed in this case.

For other environments (Linux and containers), DNS validation using Azure DNS.
