### ISSUE TITLE
[Action Required] Upgrade to App Service Acmebot v3

### ISSUE THREAD

**Issue by shibayan** [shibayan/appservice-acmebot#138]
App Service Acmebot v3 has been released since December 31, 2019. Users deploying earlier than this are encouraged to upgrade to v3.

The upgrade process is completed in 4 steps.

1. Go to Azure Portal and open Acmebot Azure Function

2. Select `Configuration` link

![image](https://user-images.githubusercontent.com/1356444/77070458-9ab75480-6a2d-11ea-97df-05f3cb3da6eb.png)

3. Update `FUNCTIONS_EXTENSION_VERSION` and `WEBSITE_RUN_FROM_PACKAGE` value.

- `FUNCTIONS_EXTENSION_VERSION`
  - `~3`
- `WEBSITE_RUN_FROM_PACKAGE`
  - `https://shibayan.blob.core.windows.net/azure-appservice-letsencrypt/v3/latest.zip`

4. Save and Exit

![image](https://user-images.githubusercontent.com/1356444/77070586-d6521e80-6a2d-11ea-8689-05520ba7cba4.png)

**Comment by davidjade** [comment]
Is there anything that need to be done in the Azure portal if you're already using v3 and an update version of appservice-acmebot v3 is released? I am a little unclear on what steps I would need to do to keep the function app always up to date when it is set to WEBSITE_RUN_FROM_PACKAGE.

**Comment by shibayan** [comment]
If you are already using the v3 version, you do not need to do anything. The latest version is always used automatically.

**Comment by Kisitova** [comment]
I`m getting 404 when trying to access https://myAppServiceName.azurewebsites.net/add-certificate

**Comment by 0xUnicorn** [comment]
Hi, I've deployed a new instance and I'm getting this error when trying to deploy a certificate on my app. 
![image](https://user-images.githubusercontent.com/17219001/82211450-23a91a00-9911-11ea-82ef-dfa48396adae.png)

**Comment by shibayan** [comment]
@0xUnicorn Could you create a separate Issue.
