### ISSUE TITLE
Bare domain extern DNS, no certificate issued

### ISSUE THREAD

**Issue by Jacob-Jan** [shibayan/appservice-acmebot#140]
Hi,

I have a domain registered outside Azure's DNS, added an A record there and a binding for the domain in Azure. 

While trying to add a certificate the following error occurs:
The activity function 'Dns01Precondition' failed: "Azure DNS zone "pitts.ai" is not found".

Any idea how to fix?

**Comment by shibayan** [comment]
You're probably requesting a Linux App Service or wildcard certificate, but then you need to manage your zone with Azure DNS. This is the current design.

**Comment by Jacob-Jan** [comment]
Okay thanks, I fixed it by manually creating a certificate with certbot and uploading it to Azure
