### ISSUE TITLE
"Deploy to Azure" to Linux app group fails

### ISSUE THREAD

**Issue by orloffm** [shibayan/appservice-acmebot#144]
"code":"WindowsWorkersNotAllowedInLinuxResourceGroup",
"message":"The requested app service plan cannot be created in the current resource group because it is hosting Linux apps. Please choose a different resource group or create a new one."

I have a resource group with a Linux-based App Service. This is what I get when pressing the "Deploy to Azure" button and filling out the form.

**Comment by shibayan** [comment]
Create a new resource group for Acmebot and deploy it. You do not need to share resource groups.
