### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by Mhm0ud** [shibayan/appservice-acmebot#148]
when I open the app to create a certificate it's told me Error: Request failed with status code 401, 
I already added the Web Plan Contributor and Website Contributor to the resource group that contains the target app service.

![image](https://user-images.githubusercontent.com/16934190/79125628-214e2000-7da7-11ea-80d9-6454631f96db.png)

![image](https://user-images.githubusercontent.com/16934190/79125680-375be080-7da7-11ea-81b4-bb07d6f2b852.png)

You see this resource because I put the template on the same resource group of the app service

**Comment by shibayan** [comment]
Have you set up App Service Authentication?

**Comment by Mhm0ud** [comment]
I was not config it in the right way, it has been solved now, thank you.
