### ISSUE TITLE
What is the price?

### ISSUE THREAD

**Issue by flixius** [shibayan/appservice-acmebot#151]
Hello,

Disclaimer: Sorry for this very untechnical issue

When I click on "Deploy Acmebot on Azure" (The button is on the Github Page @ "Getting Started"), I get redirected to the azure portal. There I have to agree the terms and conditions AND confirm the purchase. 

Unfortuntely I don't see how much a purchase of the Acmebot costs. 
Where I can see that? 

Thank you!

**Comment by shibayan** [comment]
There is no cost. Sponsors are welcome, but it's OSS, so it's free to use.

There is of course a charge for using Azure, but in my case it's about $0.2 per month.

**Comment by flixius** [comment]
Thank you for the instant response! 

I will make a donation when it works for me.
