### ISSUE TITLE
Access denied to "add-certificate"

### ISSUE THREAD

**Issue by teeto** [shibayan/appservice-acmebot#161]
I have followed all the steps but when i go to:
https://letsencrypt-icre-srdq.azurewebsites.net/add-certificate

I have a denied access 403 to that page.
Note that I can see https://letsencrypt-icre-srdq.azurewebsites.net/ (its a blue default azure page).

Do i have to log anywhere before browsing the url? i am logged into my azure account and i am admin. May be some azure active directory configuration? i am a newbie on that...

**Comment by shibayan** [comment]
Check the README to enable App Service Authentication (Easy Auth).

**Comment by teeto** [comment]
Thanks, rechecking the readme i forgot to select the option "Login with Azure Active Directory" and was selected the default option.
