### ISSUE TITLE
CleanupVirtualApplication might not be called in case of error during issuing

### ISSUE THREAD

**Issue by GeorgDangl** [shibayan/appservice-acmebot#170]
**Describe the bug**
I've just got started with the Acmebot today and ran into a problem with an older ASP.NET (the old one) application that failed to update due to entries in `system.webServer.modules` in the `web.config` file.  
I've been able to fix the issue, so future requests should work, but I noticed that the created virtual application under `/.well-known` was present and has not been cleaned up.  
This might be an issue when using applications that themselves have resources available under `.well-known`, e.g. an OpenID Connect server (see #110).  
Additionally, for us it's problematic to have the `.well-known` path not available for a time, since that essentially means a service outage for us. Would it be possible to change the virtual application to use the more tighlty scoped `.well-known/acme-challenge` path?

Also, is it possible to see when certificates are going to be renewed?

**To Reproduce**
Just use an environment that fails to make the Let's Encrypt response available under `.well-known` and try to create a new certificate.  
Looking at the code, the cleanup is not called when a failure happens earlier: https://github.com/shibayan/appservice-acmebot/blob/630b2e29455cd5687223a92beb345d50ae763820/AppService.Acmebot/RenewCertificatesFunctions.cs#L144

**Comment by shibayan** [comment]
Thank you for the report. The fix will be completed soon.
