### ISSUE TITLE
Option to enable webhooks for successfully completed events

### ISSUE THREAD

**Issue by GeorgDangl** [shibayan/appservice-acmebot#171]
**Is your feature request related to a problem? Please describe.**
In my previous experience, updating Let's Encrypt certificates has always been a brittle experience. Since I don't see any way of getting a status report of what the Acmebot is doing, it would be great if webhooks could be activated for successful events.

**Describe the solution you'd like**
The solution would be to simply send a webhook from here: https://github.com/shibayan/appservice-acmebot/blob/master/AppService.Acmebot/Internal/WebhookLifeCycleNotification.cs#L27

**Describe alternatives you've considered**
A status page would be an alternative😊

**Comment by shibayan** [comment]
I'm currently working on a related pull request. Please let us know if you have any feedback on the notification item in the meantime.

**Comment by GeorgDangl** [comment]
The PR & the message format looks great, thank you for the effort!

**Comment by shibayan** [comment]
The updates will be completed soon.
