### ISSUE TITLE
Is it possible to start the renewal check manual?

### ISSUE THREAD

**Issue by JaapMosselman** [shibayan/appservice-acmebot#175]
For some reason the function app stopt checking for renewals since more than a week.
I have restarted the app (and upgraded to v3). Will see if it starts checking again.
But is it also possible tot start that check manually?

**Comment by shibayan** [comment]
A bug in the Azure Function Runtime in some regions may have affected the execution of timers.This is now fixed, but if the update schedule does not work, restart the Function.

If you want to check for updates manually, select `RenewCertificates_Timer` from the Azure Portal and run it with the master key.

**Comment by JaapMosselman** [comment]
Thank you, I found article to do that: https://docs.microsoft.com/en-us/azure/azure-functions/functions-manually-run-non-http
But I discovered indeed that restarting also restarted the timer.
So due to the bug in the Azure Function Runtime, even it was fixed, the function was not triggered anymore until restart?

**Comment by shibayan** [comment]
I haven't investigated, but when Function Runtime crashes with an Internal Error, it may not have been running because it can't get the schedule information.
