### ISSUE TITLE
Exception when renewing certificate

### ISSUE THREAD

**Issue by JaapMosselman** [shibayan/appservice-acmebot#176]
I have 2 apps running (in our Test en Prod environment). Because of the timer problem, which I tried to solve, I updated also to v3. In Prod everything is working fine. Certificates are renewed (which was not done for more than a week, due to the timer problem).
In our Test env I now get exceptions on the RenewSiteCertificates function. I get this for 2 sites (seems the apps does not try to update the other sites, because there are errors?). For these 2 sites, I see that there is actually an new certificate installed and actived. But the function seems to have a problem to complete. Can you see what the problem is?
2020-06-03 10:18:21.498
Executing 'RenewSiteCertificates' (Reason='', Id=14a77605-23f8-42fd-bab2-d0a94785d155)
Information
2020-06-03 10:18:21.501
Site name: xxxxxxxxxxxxxx
Information
2020-06-03 10:18:21.501
Subject name: xxxxxxxxxxx
Information
2020-06-03 10:18:21.519
069986d0797b4b0a8055b3cd7fce2802:2: Function 'RenewSiteCertificates (Orchestrator)' failed with an error. Reason: Microsoft.Azure.WebJobs.Extensions.DurableTask.FunctionFailedException: The activity function 'SendCompletedEvent' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details. ---> System.NullReferenceException: Object reference not set to an instance of an object. at AppService.Acmebot.Internal.WebhookClient.SendCompletedEventAsync(String appName, String slotName, Nullable`1 expirationDate, String[] dnsNames) in /home/runner/work/appservice-acmebot/appservice-acmebot/AppService.Acmebot/Internal/WebhookClient.cs:line 24 at AppService.Acmebot.SharedFunctions.SendCompletedEvent(ValueTuple`3 input) in /home/runner/work/appservice-acmebot/appservice-acmebot/AppService.Acmebot/SharedFunctions.cs:line 489 at lambda_method(Closure , SharedFunctions , Object[] ) at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20 at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 532 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 468 at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 278 --- End of inner exception stack trace --- at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 632 at AppService.Acmebot.RenewCertificatesFunctions.RenewSiteCertificates(IDurableOrchestrationContext context, ILogger log) in /home/runner/work/appservice-acmebot/appservice-acmebot/AppService.Acmebot/RenewCertificatesFunctions.cs:line 101 at AppService.Acmebot.RenewCertificatesFunctions.RenewSiteCertificates(IDurableOrchestrationContext context, ILogger log) in /home/runner/work/appservice-acmebot/appservice-acmebot/AppService.Acmebot/RenewCertificatesFunctions.cs:line 107 at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20 at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52 at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.InvokeUserCodeAndHandleResults(RegisteredFunctionInfo orchestratorInfo, OrchestrationContext innerContext) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 150. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: LetsEncrypt-Mysolution-Test-7j6c. SlotName: Production. ExtensionVersion: 2.2.2. SequenceNumber: 82.
Error
2020-06-03 10:18:21.529
Orchestrator function 'RenewSiteCertificates' failed: The activity function 'SendCompletedEvent' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details.
Error
2020-06-03 10:18:21.529
Executed 'RenewSiteCertificates' (Failed, Id=14a77605-23f8-42fd-bab2-d0a94785d155)
Error
2020-06-03 10:18:21.531
Orchestrator function 'RenewSiteCertificates' failed: The activity function 'SendCompletedEvent' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details.
Error

**Comment by shibayan** [comment]
Thanks for the report, there was a bug that caused an error when Webhook was not configured. I'm currently working on a fix and will be releasing it soon.

**Comment by JaapMosselman** [comment]
Nice quick work!
When will it be deployed?

**Comment by shibayan** [comment]
Deploy completed. https://github.com/shibayan/appservice-acmebot/releases/tag/v3.1.6

Restart the Function App and try Renew again.

**Comment by JaapMosselman** [comment]
Everything is now working fine again! Thanks!
