### ISSUE TITLE
Azure DNS zone  is not found

### ISSUE THREAD

**Issue by luis-cortina** [shibayan/appservice-acmebot#179]
**Describe the bug**
While running the new certificate I get a failed message and pointing to this error in the log.
Azure DNS zone  is not found

**To Reproduce**
Follow documentation to create certificate.

**Environment (please complete the following information):**
 - App Service OS: Linux
 - App Service Type: Code
 - Runtime Stack: AspNetCore 3.1
 - Certificate Type: Sub-domain

**Additional context**
![image](https://user-images.githubusercontent.com/25346332/83695059-9b846f00-a5b6-11ea-84c6-7cf05aa76b94.png)

**Comment by shibayan** [comment]
Please check the following points: Azure DNS is required.

1. Make sure that the target domain is managed by Azure DNS.
2. Has the role of `DNS Zone Contributor` been assigned to the Azure DNS zone?
