### ISSUE TITLE
CheckHttpChallenge error

### ISSUE THREAD

**Issue by JaapMosselman** [shibayan/appservice-acmebot#181]
For one certificate renewal operation, I get this error:

`Exception while executing function: CheckHttpChallenge GFDpPWHYUHjcRygyePzJXvdCaMJtCnZHc_pjtRIE31Q.YSLywWxL5kLK2NVRU84pZYLVUlExIkAPrTN8A47aVrI value is not correct.`

What is the problem? And how should I solve it?

**Comment by shibayan** [comment]
This error can occur if the virtual application configuration takes a long time to be reflected by Azure.

I'm releasing a mitigated version of this issue, so please try again after restarting Function.

**Comment by JaapMosselman** [comment]
I restarted the function app, but I stille get the error. See the logging below. Problem is also that I can't see in this logging which site is giving problems. Would be handy to log the sitename in the first informational logging of RenewSiteCertificates.

2020-06-08 09:27:16.040
Executing 'RenewSiteCertificates' (Reason='', Id=a4c8033e-7fd9-4542-a469-7127578f466a)
Information

2020-06-08 09:27:16.134
Orchestrator function 'RenewSiteCertificates' failed: The orchestrator function 'IssueCertificate' failed: "The activity function 'CheckHttpChallenge' failed: "GFDpPWHYUHjcRygyePzJXvdCaMJtCnZHc_pjtRIE31Q.YSLywWxL5kLK2NVRU84pZYLVUlExIkAPrTN8A47aVrI value is not correct.". See the function execution logs for additional details.". See the function execution logs for additional details.
Error

2020-06-08 09:27:16.134
Executed 'RenewSiteCertificates' (Failed, Id=a4c8033e-7fd9-4542-a469-7127578f466a)
Error

2020-06-08 09:27:16.136
Orchestrator function 'RenewSiteCertificates' failed: The orchestrator function 'IssueCertificate' failed: "The activity function 'CheckHttpChallenge' failed: "GFDpPWHYUHjcRygyePzJXvdCaMJtCnZHc_pjtRIE31Q.YSLywWxL5kLK2NVRU84pZYLVUlExIkAPrTN8A47aVrI value is not correct.". See the function execution logs for additional details.". See the function execution logs for additional details.
Error

**Comment by shibayan** [comment]
A new version has been released with further mitigation built in. I have also fixed the logging issues that were reported.

I hope it all works with this release.

**Comment by JaapMosselman** [comment]
Thank you much! With the extra logging I could easily track the route cause of my problem.
It wasn't in fact a problem in your code I think, but on our site.
I had a site which originally had 4 custom domains, so a certificate with 4 subjects was created. But afterwards 2 of these custom domains where moved to another site. But the certificate was not regenerated, so the certificate with the 4 subjects was still active. 
So I generated a new certificate and I guess the errors are now away.
