### ISSUE TITLE
No Option for Web Plan Contributor

### ISSUE THREAD

**Issue by matthewdgregory** [shibayan/appservice-acmebot#183]
**Describe the bug**
I have added Website Contributor to my App, back cant see Web Plan Contributor

As in the documentation the dropboxes are blank
![Annotation 2020-06-06 085729](https://user-images.githubusercontent.com/48640307/83922066-d1526f00-a7d3-11ea-88f5-9bfc97415204.png)

**Comment by shibayan** [comment]
You need to attach it to the resource group or the App Service Plan.

https://github.com/shibayan/appservice-acmebot#3-add-access-control-iam-to-the-target-resource-group
