### ISSUE TITLE
modules in <system.webServer> inherited from base app

### ISSUE THREAD

**Issue by KaptenJon** [shibayan/appservice-acmebot#184]
In one of our applications we use modules. Those modules are inherited by the .well.known webapp.  And because they are not configured correctly the renewal process gets respond with 500. 

When I add code to the .well.known app web.config to remove the custom modules the renewal process works. But next time this was removed once again resulting in 500 errors in the renewal process.

Please att code to the well.known. app web.config that remove all modules and add the ones you need if any.

**Comment by shibayan** [comment]
Adding `inheritInChildApplications="false"` in root `web.config`
https://github.com/shibayan/appservice-acmebot#troubleshooting

**Comment by KaptenJon** [comment]
Thank you, Might not be a solution for us though we have other applications. But I guess we need to investigate and modify some.
