### ISSUE TITLE
Stopped sites should be ignored

### ISSUE THREAD

**Issue by JaapMosselman** [shibayan/appservice-acmebot#187]
Sorry to bother you again :-), but I have 1 last issue for now.
I have a site which is for some reason stopped for a longer time. The certificate is almost expired, so your bot is trying to renew it. But of course that failes, as the site is not running.
So  I whould suggest that the RenewCertificate function should just skip sites which are not in a running state.

**Comment by shibayan** [comment]
Thank you for your great feedback. Add a process to check the status of Web App and determine whether to update.
