### ISSUE TITLE
Recycling an existing Domain used in acmebot / letsencrypt results in an Http01Authorization problem

### ISSUE THREAD

**Issue by skulawik** [shibayan/appservice-acmebot#189]
After adding a "random" domain to the Windows App Service the .well-known path has been created and the acme-challenge created. When recycling one previously used DNS entry, the acme-challenge is not being updated in the file system and the following error comes up:

`Orchestrator function 'AddCertificate' failed: The orchestrator function 'IssueCertificate' failed: "The activity function 'Http01Authorization' failed: "Sequence contains no matching element". See the function execution logs for additional details.". See the function execution logs for additional details.`

Unfortunately tracing is quite hard as we miss detailed descriptions in the log:

`2020-06-10 06:24:19.151 Executing 'Http01Authorization' (Reason='', Id=a3410a8e-b737-4d73-a5e9-edc260302432) Information 2020-06-10 06:24:19.914 Sequence contains no matching element Error 2020-06-10 06:24:19.914 Executed 'Http01Authorization' (Failed, Id=a3410a8e-b737-4d73-a5e9-edc260302432) Error 2020-06-10 06:24:19.917 Sequence contains no matching element Error`

**Comment by shibayan** [comment]
I have decided not to take action on this issue.

- HTTP-01 is generally preferred over DNS-01 for its simplicity
- It's too late to find out if only DNS-01 is available after the order to Let's Encrypt
- Key Vault Acmebot is a better fit for this use case
