### ISSUE TITLE
Creating DNS Certificates with Cloudflare

### ISSUE THREAD

**Issue by GeorgDangl** [shibayan/appservice-acmebot#196]
**Is your feature request related to a problem? Please describe.**
For our sites, we're using [Cloudflare](https://www.cloudflare.com/) for DNS management. This has been working great with the file based challenge on our Windows sites, but poses a problem for App Service on Linux (or Docker) where we have to use Azure DNS.

Is there an easy way to extend the AcmeBot to either use the Cloudflare DNS API or another workaround?

**Comment by shibayan** [comment]
I'm working on a Key Vault version of Acmebot to support external DNS provider, such as Cloudflare.
https://github.com/shibayan/keyvault-acmebot/issues/76

Please consider using this for Linux / Docker.

**Comment by GeorgDangl** [comment]
Thank you, I hadn't seen that!
