### ISSUE TITLE
CheckIsReady ACME domain validation is pending

### ISSUE THREAD

**Issue by IamJapanese** [shibayan/appservice-acmebot#198]
**Describe the bug**
証明書の更新時に次の関数でエラーが発生しています。証明書を作成してから初めての更新になります。
- RenewSiteCertificates
- IssueCertificate
- CheckIsReady

RenewSiteCertificates 関数では、次のエラーが発生しています。
`DurableTask.Core.Exceptions.OrchestrationFailureException`
**Exception** `while executing function: RenewSiteCertificates Orchestrator function 'RenewSiteCertificates' failed: The orchestrator function 'IssueCertificate' failed: "The activity function 'CheckIsReady' failed: "Invalid order status. Required retry at first.". See the function execution logs for additional details.". See the function execution logs for additional details. `

CheckIsReady 関数では、次のエラーが発生しています。
`AppService.Acmebot.Internal.RetriableActivityException`
**Message**	`Exception while executing function: CheckIsReady ACME domain validation is pending.`
**Exception type**	`AppService.Acmebot.Internal.RetriableActivityException`
**Failed method**	`AppService.Acmebot.SharedFunctions+<CheckIsReady>d__23.MoveNext`
**Severity level**	`Error`
**Telemetry type**	`exception`
**Operation name**	`CheckIsReady`
・・・
**SDK version**	`azurefunctions: 3.0.13901.0`
**Sample rate**	`1`
**Problem Id**	`AppService.Acmebot.Internal.RetriableActivityException at AppService.Acmebot.SharedFunctions+<CheckIsReady>d__23.MoveNext`
**Assembly**	`AppService.Acmebot, Version=3.1.12.0, Culture=neutral, PublicKeyToken=null`

**Environment (please complete the following information):**
 - App Service OS:  Windows
 - App Service Type: Web App Standard
 - Runtime Stack: .NET Core
 - Certificate Type: 次の 2 つの形式に対して作成したので、ワイルドカードは使用していません。
1. contoso.hoge
2. www.contoso.hoge
- **Deployment Slot**：production
- **Use IP Based SSL**：No
のように指定して作成しました。

**Additional context**
Azure DNS は使用していませんが、証明書の作成は正常に行われました。
エラー内容にある、ドメインの検証が保留状態という状況が理解できません。
証明書は発行されてカスタムドメインと SNI SSL でバインディングも行われています。
なにか手動で承認する必要があるのでしょうか？

元々同じドメインに対して、別の App Service で拡張機能の方の Let's Encrypt を使用していました。
その App Service を丸ごと削除して、今回こちらの方で証明書を作成しています。
それが原因しているのでしょうか？

よろしくお願いします。

**Comment by shibayan** [comment]
これは意図したリトライの実行中なので、証明書が正常に発行されているなら無視してかまいません。
