### ISSUE TITLE
Add certificate failing with web app container

### ISSUE THREAD

**Issue by jsutes** [shibayan/appservice-acmebot#199]
**Describe the bug**
I set up the appservice-acmebot about a week ago.  I successfully used it with two linux web app containers.  Now when I try the same steps with some more linux container web apps, I get an error message in the browser:

> Orchestrator function 'AddCertificate' failed: The orchestrator function 'IssueCertificate' failed: "The activity function 'Dns01Authorization' failed: "Sequence contains no matching element". See the function execution logs for additional details.". See the function execution logs for additional details.

I've tried with two different domains, two different linux web app containers, and two different traditional windows web apps.  When the domains are added to the traditional web apps, adding the certificates succeeds.  When the domains are added to the container web apps, I keep getting the error message above.

I've tried getting more information from the logs, but I haven't found anything more detailed than the error message that gets sent to the browser.

I have two container web apps that used the appservice-acmebot successfully last week.  I don't think there is anything substantially different between the apps last week and the apps this week.

**To Reproduce**
1. Go to 'https://acmebot-3csv.azurewebsites.net/add-certificate'
2. Select the resource group, app name, deployment slot, DNS name, Use IP Based SSL: No
3. Click 'Submit'
4. See error above

**Environment (please complete the following information):**
 - App Service OS: Linux
 - App Service Type: Container
 - Runtime Stack: nginx angular
 - Certificate Type: not sure

**Comment by shibayan** [comment]
Have you ever used HTTP-01 validation (ex: using Windows App Service) to issue a Let's Encrypt certificate for an error domain?

**Comment by jsutes** [comment]
Hello shibayan, thank you for replying.

These domains are about 2 years old (purchased through Azure) and I had been using them with Windows App Service.  I used a different public github project to issue Let's Encrypt certificates at that time which could have been using HTTP-01 validation. I can't remember the name of that github project but I can keep looking.

Web setup is not my area of expertise, so I apologize if I'm not answering your question very well.

**Comment by shibayan** [comment]
Due to limitations of Let's Encrypt, once a domain has been issued a certificate using HTTP-01, it cannot be issued using DNS-01. This means that this only affects Windows and Linux App Services when they are used at the same time on the same domain name.

https://community.letsencrypt.org/t/cant-do-http-01-challenge-after-dns-01-challenge/117085

**Comment by jsutes** [comment]
Thank you for pointing me in the right direction. Do you know if using DNS-01 will be allowed once the old certificate that used HTTP-01 expires?
I was able to install certbot and manually get a certificate using dns. Then uploaded the certificate through the Azure portal. So I'm good for the next 3 months. I'm hoping I can successfully certify using appservice-acmebot once enough time passes.

**Comment by shibayan** [comment]
Since the accounts are different in certbot and acmebot, the authentication status would not have been affected.

Perhaps initializing your acmebot account information will allow you to issue certificates in DNS-01. You can initialize your account by deleting the `D:\home\.acme` directory.

**Comment by jsutes** [comment]
Thank you, that makes sense. I reinitialized my acmebot account info as you described and now I can certify those domains using acmebot.
Thanks for helping, especially since this issue was caused by my lack of understanding of letsencrypt and not really an issue with your acmebot.
