### ISSUE TITLE
Unable to install in azure Gov Cloud

### ISSUE THREAD

**Issue by seanrallSRS** [shibayan/appservice-acmebot#207]
I have been trying to get this to work on Azure US Gov Cloud and keep hitting this error. 
`{
   "code":"DeploymentFailed",
   "message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
   "details":[
      {
         "code":"BadRequest",
         "message":"
{\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"There was a conflict. The remote name could not be resolved: 'st5dt6nvbwf7wiofunc.file.core.windows.net'\",\r\n 
\"Target\": null,\r\n \"Details\": [\r\n {\r\n \"Message\": \"There was a conflict. The remote name could not be resolved: 'st5dt6nvbwf7wiofunc.file.core.windows.net'\"\r\n },\r\n {\r\n \"Code\": \"BadRequest\"\r\n },\r\n {\r\n \"ErrorEntity\": {\r\n \"ExtendedCode\": \"01020\",\r\n \"MessageTemplate\": \"There was a conflict. {0}\",\r\n \"Parameters\": [\r\n \"The remote name could not be resolved: 'st5dt6nvbwf7wiofunc.file.core.windows.net'\"\r\n ],\r\n \"Code\": \"BadRequest\",\r\n \"Message\": \"There was a conflict. The remote name could not be resolved: 'st5dt6nvbwf7wiofunc.file.core.windows.net'\"\r\n }\r\n }\r\n ],\r\n \"Innererror\": null\r\n}"
      }
   ]
}`

`{
    "Code": "BadRequest",
    "Message": "There was a conflict. The remote name could not be resolved: 'st5dt6nvbwf7wiofunc.file.core.windows.net'",
    "Target": null,
    "Details": [
        {
            "Message": "There was a conflict. The remote name could not be resolved: 'st5dt6nvbwf7wiofunc.file.core.windows.net'"
        },
        {
            "Code": "BadRequest"
        },
        {
            "ErrorEntity": {
                "ExtendedCode": "01020",
                "MessageTemplate": "There was a conflict. {0}",
                "Parameters": [
                    "The remote name could not be resolved: 'st5dt6nvbwf7wiofunc.file.core.windows.net'"
                ],
                "Code": "BadRequest",
                "Message": "There was a conflict. The remote name could not be resolved: 'st5dt6nvbwf7wiofunc.file.core.windows.net'"
            }
        }
    ],
    "Innererror": null
}`

From my understanding this file `st5dt6nvbwf7wiofunc.file.core.windows.net` is hosted in an Azure DC and files are only available from inside the Azure DC, witch makes this error correct in the sense that Azure and Azure Gov are separate clouds. So what is this this file? and do I have to to run something manually to build this project instead of a one click deployment?

Any help would be nice.

**Comment by shibayan** [comment]
I'm not familiar with US Gov Cloud, so I have a question for you.

Are all Azure resources (Function / Storage / App Insights) created? Or is only Function not created?

**Comment by seanrallSRS** [comment]
It looks like all steps complete but fails at the Sites creation
![image](https://user-images.githubusercontent.com/56175796/89920407-37cb8300-dbb1-11ea-9343-bb1ce68b45b8.png)

I ran the same script in regular Azure to see all whats created

**Comment by shibayan** [comment]
Thank you for sharing this information. Now I can add support for the national cloud.

**Comment by seanrallSRS** [comment]
If it helps here is the verbose deployment details
[Deployment-Microsoft.Template-gov.zip](https://github.com/shibayan/appservice-acmebot/files/5058060/Deployment-Microsoft.Template-gov.zip)

**Comment by shibayan** [comment]
A preview version of Azure Government support has been released. You can use the following link to deploy it.

https://portal.azure.us/#create/Microsoft.Template/uri/https%3a%2f%2fgist.githubusercontent.com%2fshibayan%2fe30fdaac0283f334d87210efd0bac9d2%2fraw%2f283fd17e268ca623be25db4bb31491c610132d13%2fazuredeploy.json

I have not been able to create an Azure Government account, so I have not been able to verify that it works. If you encounter any errors, please report them to me and I can fix them.

**Comment by seanrallSRS** [comment]
I have been able to get it installed and can verify I can run the app in US gov cloud. 
Now I am testing to make sure it can register a new certificate and renew one. 

Thanks for help!
