### ISSUE TITLE
get-sites-information seems to be timing out

### ISSUE THREAD

**Issue by JefRH1** [shibayan/appservice-acmebot#209]
I have installed this under 2 different Subscriptions / Resource Groups.  I have been able to get it working with a Resource Group that has 15 resources in it.

However, I have a Resource Group that has 400+ resources in it and on that function app, the get-sites-information call seems to be timing out.  It will run for 30 sections then return the following result:

{"id":"[clientidremoved]","statusQueryGetUri":"https://func-acmebot-5vrz.azurewebsites.net/runtime/webhooks/durabletask/instances/[clientidremoved]?taskHub=DurableFunctionsHub&connection=Storage&code=[coderemoted]/bfg==","sendEventPostUri":"https://func-acmebot-5vrz.azurewebsites.net/runtime/webhooks/durabletask/instances/[clientidremoved]/raiseEvent/{eventName}?taskHub=DurableFunctionsHub&connection=Storage&code=[coderemoted]/bfg==","terminatePostUri":"https://func-acmebot-5vrz.azurewebsites.net/runtime/webhooks/durabletask/instances/[clientidremoved]/terminate?reason={text}&taskHub=DurableFunctionsHub&connection=Storage&code=[coderemoted]/bfg==","purgeHistoryDeleteUri":"https://func-acmebot-5vrz.azurewebsites.net/runtime/webhooks/durabletask/instances/[clientidremoved]?taskHub=DurableFunctionsHub&connection=Storage&code=[coderemoted]/bfg=="}

This might be more of a feature request as I assume its related to the required amount of time to query and retrieve that number of items, but I'm wondering if you or I can modify something to get this working?

**Comment by shibayan** [comment]
Thanks for the feedback.

 it looks like using the Resource Graph could be a significant improvement, so I'm going to switch implementations to solve this problem.

**Comment by JefRH1** [comment]
I confirmed this fixed my issue.  Thanks!
