### ISSUE TITLE
issue with Microsoft.AspNet.TelemetryCorrelation

### ISSUE THREAD

**Issue by jdevillard** [shibayan/appservice-acmebot#211]
**Describe the bug**
I use the appservice-acmebot to configure LetsEncrypt on Azure Web App that use App Insight.
I've issue on the call to .well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxx with the following error 

Could not load file or assembly 'Microsoft.AspNet.TelemetryCorrelation' or one of its dependencies. The system cannot find the file specified.

I've solve the issue by adding :

   <modules runAllManagedModulesForAllRequests="true">
      <remove name="FormsAuthentication" />
      <remove name="TelemetryCorrelationHttpModule" />
      <remove name="ApplicationInsightsWebTracking" />
    </modules>

to the web.config present in the .well-know folder. But I've to change the config file for each renew.

**To Reproduce**
1. Create a App Service with App Insight 
2. Be sure to have Web.Config with the following element in the root : 

    <modules runAllManagedModulesForAllRequests="true">
         <add name="TelemetryCorrelationHttpModule" type="Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule, Microsoft.AspNet.TelemetryCorrelation" preCondition="integratedMode,managedHandler" />
        <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />
    </modules>

3. Install the azure function
4. Try to create or renew certificate.

**Environment (please complete the following information):**
 - App Service OS: Windows
 - App Service Type: Web site
 - Runtime Stack: .NET v4.7
 - Certificate Type: sub-domain

I've try to use  <location path="." inheritInChildApplications="false">  but nothing seems to work (or I misuse it).

Is there a way to customize the web.config used in the .well-known folder ? So this new file will be use for each create/renew

Thanks

**Comment by shibayan** [comment]
I have not been able to reproduce this issue. Have you tried adding the `inheritInChildApplications="false"` setting?

**Comment by jdevillard** [comment]
Hello, 

thanks for the answer, yes I've try with  <location path="." inheritInChildApplications="false"> but without success.

I will try to create a sample to reproduce this issue

**Comment by shibayan** [comment]
The relevant issues can now be resolved by the user. Please see #222
