### ISSUE TITLE
Ability to Switch to/from DNS-01

### ISSUE THREAD

**Issue by Rizen-Kris** [shibayan/appservice-acmebot#213]
**Is your feature request related to a problem? Please describe.**
Need to have a way of viewing/managing existing certs. If you need to switch a cert to "Force DNS-01" there does not appear to be a way. If you try to redo the cert as DNS-01 then it gives an error:

Orchestrator function 'AddCertificate' failed: The orchestrator function 'IssueCertificate' failed: "The activity function 'Dns01Authorization' failed: "Simultaneous use of HTTP-01 and DNS-01 for authentication is not allowed.". See the function execution logs for additional details.". See the function execution logs for additional details.

**Comment by shibayan** [comment]
Duplicated https://github.com/shibayan/appservice-acmebot/issues/199#issuecomment-665093876
