### ISSUE TITLE
Allow checkbox option to preconfigure .well-known virtual application

### ISSUE THREAD

**Issue by samrueby** [shibayan/appservice-acmebot#222]
**Is your feature request related to a problem? Please describe.**
Yes. The way this function works, it creates a virtual application within your parent application, installs a web.config to be able to serve extensionless files, and then writes the [extensionless] acme verification file so that the verification can occur. The problem is with IIS's web.config inheritance. Since this function create a virtual application of the parent site, this means that the web.config of the parent site is inherited. Unfortunately, it's not good enough to just include `<location inheritInChildApplications=”false”>` in the parent application's config. You may still need to include some undo-configurations in the child web.config (e.g. the .well-known application that this function creates) in order to be able to serve anything at all. (What happens is a YSOD (Yellow Screen of Death) appears for any request to the .well-known virtual application).

A real-example is Sitefinity sites. Progress Telerik tells users the slightly-complicated process to be able to have virtual applications within a parent Sitefinity application at all: https://www.progress.com/documentation/sitefinity-cms/run-a-sitefinity-instance-as-parent-or-child-of-an-asp-net-application.  TL;DR: it requires you to modify the parent web.config a little bit, and requires some special undo-configuration in the child web.config. Both steps are required or any child virtual applications won't load at all.

Unfortunately even if I create the .well-known virtual application and set the proper web.config, this function overwrites the web.config with an invalid one. And then also deletes my .well-known virtual application after its attempt.

**Describe the solution you'd like**
I think the easiest possible solution for you would to be include a checkbox somewhere that allows me to configure the .well-known virtual application with the proper web.config myself. That way you don't have to deal with all of the ways a web.config can go wrong. With that checkbox checked, you wouldn't create the .well-known virtual application, wouldn't create the web.config, and wouldn't delete the .well-known virtual application after.

**Describe alternatives you've considered**
I've tried hacking it multiple ways, but it is not possible. Web.configs can't be read-only App Service. I can't completely remove permission because you need to be able to write the acme verification file.

**Comment by shibayan** [comment]
You just need to avoid overwriting the web.config by the app, and it doesn't matter if the app deletes the virtual application.

**Comment by samrueby** [comment]
Yes, overwriting the web.config is the main issue, and deleting the virtual application is only minorly annoying when testing to make sure things are working properly.

**Comment by shibayan** [comment]
If I come up with a good way to prevent overwriting, I will implement it. I don't want to add more checkboxes.

**Comment by samrueby** [comment]
If you can describe how you'd like it implemented, I would be interested in making a pull request.

**Comment by shibayan** [comment]
v3.2.0 Released.
