### ISSUE TITLE
Cert not renewing / can no longer deploy new cert

### ISSUE THREAD

**Issue by AuXDubz** [shibayan/appservice-acmebot#224]
Access permissions look to be correct and have previously deployed a cert to this app service resource

So I set up a new dev slot with vanilla settings and tried again, still failed.  The only difference I can tell between when I originally deployed the cert a month or two ago is that we now have a 'Force DNS-01 Challenge' option, so there looks to have been an update recently. 

Now with this new dev slot, there is no IP restrictions or login auth page in front of the app. I have checked the files and cannot find any trace of LetsEncrypt - is this a sign that the function app is failing to write? 

![image](https://user-images.githubusercontent.com/971464/93104589-f6456080-f6a5-11ea-9e10-0223eddf5665.png)

Please advise.

**Comment by shibayan** [comment]
You need to determine why the App Service is returning a 500 Internal Server Error in the response file for Let's Encrypt.

You can identify this by checking App Service logs, Application Insights, or eventlog.xml using Kudu.
