### ISSUE TITLE
How do renewals work?

### ISSUE THREAD

**Issue by JefRH1** [shibayan/appservice-acmebot#237]
I'm not seeing my App Services that have LetsEncrypt certs getting updated.  Is there documentation on how this works?  Should there be a log somewhere that shows what Apps have been checked and/or updated?  Also does the cert need to be created using the Add-Cert method in the function app or will it update any App Service that has a LetsEncrypt cert added by any external means?

**Comment by shibayan** [comment]
Only certificates issued by Acmebot will be processed for renewal approximately 30 days in advance.Renewals are only processed on Mondays, Wednesdays, and Fridays, so it's not always 30 days in advance.

All execution logs can be viewed at Application Insights.
