### ISSUE TITLE
Getting 403 with - Exception while executing function: GetResourceGroups

### ISSUE THREAD

**Issue by henrikrox** [shibayan/appservice-acmebot#241]
I have deployed my acmebot in a separate subscription from my web apps.

I have done eveyrthing correctly and web page is showing after login, i see from app insights i get a 403 when trying to use the drop down meny.

From logs:
Exception while executing function: GetResourceGroups The client '17xxxx-xxxxxx-xxxxx-xxxxx' with object id '17xxxx-xxxxxx-xxxxx-xxxxx' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/Xx' or the scope is invalid. If access was recently granted, please refresh your credentials. 

I dont know that clientid, But the the subscription is not where i given the two IAM web role assignments to the function app. Its insead the subscription id to where the function app lives. Which is weird?

**Comment by shibayan** [comment]
Change the `Acmebot:SubscriptionId` in App Settings in Azure Functions to point to the correct subscription.
