### ISSUE TITLE
Exception while executing function: CheckHttpChallenge http://X/.well-known/acme-challenge/FGS7upCz0jM5r7i-rpp0Un-33eJRgACk4KRINWnlXu8 is InternalServerError status code.

### ISSUE THREAD

**Issue by henrikrox** [shibayan/appservice-acmebot#243]
I see from the readme this is mentioned,

I have the .well known path set in the app service in path mappings, i also have this 
![image (5)](https://user-images.githubusercontent.com/6884716/98083978-705ebe00-1e7b-11eb-84b6-2d6c88fad892.png)

based on the readme file i should put something into the location path (see picture over)
https://www.hanselman.com/blog/ChangingASPNETWebconfigInheritanceWhenMixingVersionsOfChildApplications.aspx

**Comment by henrikrox** [comment]
i notice that the path mappings gets removed each time i try to run the acmebot and get a certificate. Really having a had time understanding whats wrong. 
![2020-11-04 10_07_06-app-eldreombudet-internett-test - Microsoft Azure](https://user-images.githubusercontent.com/6884716/98091305-840f2200-1e85-11eb-9677-1c5a60882dc2.png)

**Comment by shibayan** [comment]
Problems have been reported to occur with applications like Umbraco.

You need to follow the instructions at the following URL to create a `web.config` that cancels the value set in your root `web.config`

https://github.com/shibayan/appservice-acmebot#the-case-where-you-want-to-use-your-own-webconfig

**Comment by luis-cortina** [comment]
This was frustrating enough so I think I'll post a solution here specific to Umbraco, basically add a new Umbraco Api controller to the root of the project and add following code(I literally tried everything else, but either the challenged worked or umbraco)
```

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Umbraco.Core.Composing;
using Umbraco.Web.WebApi;

namespace RoseErosion
{
    //https://our.umbraco.com/forum/extending-umbraco-and-using-the-api/83794-webapi-routing
    public class CustomApiRoutesComposer : ComponentComposer<CustomApiRoutesComponent>
    {
    }

    public class CustomApiRoutesComponent : IComponent
    {
        public void Initialize()
        {
            GlobalConfiguration.Configuration.MapHttpAttributeRoutes();
            GlobalConfiguration.Configuration.Initializer(GlobalConfiguration.Configuration);
        }

        public void Terminate()
        {
            throw new NotImplementedException();
        }
    }

    public class LetsEncryptController : UmbracoApiController
    {

        //https://gist.github.com/dibble-james/f47b0cba3494381588482c7f185861bf
        //https://stackoverflow.com/questions/11581697/is-there-a-way-to-force-asp-net-web-api-to-return-plain-text
        [HttpGet]
        [Route(".well-known/acme-challenge/{fileName}")]
        public HttpResponseMessage GetChallenge(string fileName)
        {
            try
            {
                Logger.Info(this.GetType(), $"GetChallenge: Entering for file name: {fileName}");
                var currentPath = HttpContext.Current.Server.MapPath("~");
                Logger.Info(this.GetType(), $"GetChallenge:  currentPath {currentPath}");
                var relativePath = $"..\\.well-known\\acme-challenge\\{fileName}";
                Logger.Info(this.GetType(), $"GetChallenge:  relativePath {relativePath}");
                var fullPath = Path.GetFullPath(Path.Combine(currentPath, relativePath));
                Logger.Info(this.GetType(), $"GetChallenge:  fullPath {fullPath}");
                string result = File.ReadAllText(fullPath);
                Logger.Info(this.GetType(), $"GetChallenge:  result {result}");
                var resp = new HttpResponseMessage(HttpStatusCode.OK);
                resp.Content = new StringContent(result, System.Text.Encoding.UTF8, "text/plain");
                return resp;
            }
            catch (Exception ex)
            {

                Logger.Error(this.GetType(), ex, ex.Message);
                throw;
            }

        }
    }
}
```

**Comment by christophborndigital** [comment]
There are two approaches you can take to make this work:

1. Wrap the sections `system.web` and `system.webServer` of your `web.config` in `<location path="." inheritInChildApplications="false">` tags. This works, but will be a pain for Umbraco upgrades and if you're using web.config transforms, unless you somehow apply this on your deployment pipeline.
2. Upload a `web.config` file to the `.well-known` folder that overrides/resets some of the settings from `system.web` and `system.webServer`. I ended up with this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <validation validateIntegratedModeConfiguration="false"/>
    <modules runAllManagedModulesForAllRequests="true">
      <remove name="WebDAVModule"/>
      <remove name="UmbracoModule"/>
      <remove name="ScriptModule"/>
      <remove name="ClientDependencyModule"/>
      <remove name="FormsAuthentication"/>
      <remove name="ImageProcessorModule"/>
      <remove name="TelemetryCorrelationHttpModule" />
      <remove name="ApplicationInsightsWebTracking" />
    </modules>
    <handlers>
      <clear />
      <add name="StaticFile" path="*" verb="*" modules="StaticFileModule" resourceType="Either" requireAccess="Read" />
    </handlers>
    <staticContent>
      <remove fileExtension="." />
      <mimeMap fileExtension="." mimeType="text/plain" />
    </staticContent>
    <rewrite>
      <rules>
        <clear />
      </rules>
    </rewrite>
  </system.webServer>
  <system.web>
    <compilation>
      <assemblies>
        <clear />
      </assemblies>
    </compilation>
    <membership defaultProvider="">
      <providers>
        <clear />
      </providers>
    </membership>
    <roleManager enabled="false">
      <providers>
        <clear />
      </providers>
    </roleManager>
    <authorization>
      <allow users="*"/>
    </authorization>
  </system.web>
</configuration>
```

Note that you should also upload a file called `configured` (no extension) to the `.well-known` folder, to tell acmebot not to overwrite your modified `web.config`.

With either approach, you will also need to tell Umbraco to ignore the `.well-known` folder by adding it to the setting `Umbraco.Core.ReservedPaths` (Umbraco 8).

See here for a comment that got me on the right track:

https://our.umbraco.com/forum/using-umbraco-and-getting-started/104756-umbraco-8-plus-appservice-acmebot-lets-encrypt#comment-326967
