### ISSUE TITLE
Question: How to change LetsEncrypt:Contacts

### ISSUE THREAD

**Issue by JaapMosselman** [shibayan/appservice-acmebot#247]
In the application settings of the Function App I have change the LetsEncrypt:Contacts setting.
But I still receive notifications on the old email address.
How is that new address propagated to Let's Encrypt?
Or how should I do that?

With regards,
Jaap

**Comment by shibayan** [comment]
Thank you for your feedback.

There was no way to update the contact information on the account, so I implemented it. Starting with the next version, if your email address has changed, your contact information will be updated automatically.
