### ISSUE TITLE
all apps in a app service plan are not shown

### ISSUE THREAD

**Issue by NoOpArmyAshkan** [shibayan/appservice-acmebot#257]
**Describe the bug**
I have multiple apps in a plan. one of them has both staging and prod deployment slots. only one of the 3 apps in the plan are shown in the box to select. some of my sub-domains are on the other apps

**Environment (please complete the following information):**
 - App Service OS: windows
 - App Service Type: Code
 - Runtime Stack: . .NET v4.7
 - Certificate Type: sub-domain

Hope this time is a real issue. one of the apps not shown doesn't run anything and only has a webjob but the other is our ASP.NET API site

**Comment by shibayan** [comment]
Check the following three points. Perhaps a configuration omission or a problem in the Azure API.

1. Make sure you have added a custom domain to the App Service
2. Make sure the IAM settings are correct
3. If you don't see anything other than the production slot, it may be a bug in Azure API

**Comment by NoOpArmyAshkan** [comment]
I was sure of 1 and 2 of course. removed the domain from another app service and it did not show up. also stopped one and it did not show up.
on 2 i was sure since all others from the same resource group were being shown

It got fixed when i moved the domain to production slot. Should i send a PR for the readme file and add it as a limitation? Also again , would like to help a bit on docs if you have anything specific in mind.

**Comment by shibayan** [comment]
It seems to be a issue in the Azure REST API for sure. This is because the following APIs have suddenly stopped returning responses containing slots for a few days.

https://docs.microsoft.com/en-us/rest/api/appservice/webapps/listbyresourcegroup

I have contacted support, but it seems to take some time.

**Comment by NoOpArmyAshkan** [comment]
My problem is resolved so no rush on my side. However I don't know if you want to close this or not so I'll not touch it :)

**Comment by shibayan** [comment]
I have added code to mitigate this issue, so it will be closed at the time of the merge.
