### ISSUE TITLE
Support Key Vault

### ISSUE THREAD

**Issue by shibayan** [shibayan/appservice-acmebot#26]
https://blogs.msdn.microsoft.com/appserviceteam/2016/05/24/deploying-azure-web-app-certificate-through-key-vault/

**Comment by kbdavis07** [comment]
Is this still planned? To support Key Vault?

Thanks,

Brian Keith Davis

**Comment by shibayan** [comment]
Can you try the Key Vault version? You will need Azure DNS.
https://github.com/shibayan/azure-keyvault-letsencrypt

App Service has been updated and Key Vault Certificates are easily available from the Azure Portal.
![image](https://user-images.githubusercontent.com/1356444/58268685-de671080-7dc0-11e9-9ba6-efa20bf5e1ee.png)

When renewing a certificate with Key Vault, App Service is also renewed.

**Comment by shibayan** [comment]
By using https://github.com/shibayan/keyvault-acmebot
