### ISSUE TITLE
Update documentation for IAM steps

### ISSUE THREAD

**Issue by Jehoel** [shibayan/appservice-acmebot#264]
**Describe the bug**

As of commit `05da9c4`, the `README.md` uses old screenshots that refer to Azure Portal UI elements that have changed.

The content under the "Add access control (IAM) to the target resource group" heading needs to be changed to:

1. Open the IAM pane of the Resource Group (what if you want to grant access to individual Azure App Services?)
2. Click the "Add" button in the top toolbar of the IAM pane
3. Click "Add role assignment": 
![image](https://user-images.githubusercontent.com/1693078/104438041-6248b000-5544-11eb-9893-9c6b4f2f2c96.png)

And update the screenshot showing the added permissions as it's now displayed under the "Role assignments" tab which now looks very different to how it does in the posted screenshot.

**Comment by shibayan** [comment]
By creating a Pull Request, you can make the documentation better.

Azure Portal is changing so fast that I don't want to spend my work time trying to keep up.
