### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by nvmkpk** [shibayan/appservice-acmebot#267]
How do I deploy this to azure manually or is there a way to disable app insights? The region I am trying to deploy to appears to not support Application Insights and I am running into an error.

**Comment by shibayan** [comment]
Manual deployment is not recommended for anyone other than Azure professionals. You should only be able to select regions that are available through Azure, but maybe there is some problem.

This app is designed to be independent of the region where it is deployed, so it is recommended to deploy to the region with the lowest price. In fact, I've deployed Acmebot in West US 2 for the Japan East App Service.

**Comment by nvmkpk** [comment]
I am selecting a resource group and not the region.

**Comment by shibayan** [comment]
Creating a new resource group will solve the problem as the appropriate region will be used.
