### ISSUE TITLE
Azure Government Active Directory has no "Express" management mode

### ISSUE THREAD

**Issue by ffcruz85** [shibayan/appservice-acmebot#273]
Hello and thanks for your work.

I have a question here - your documentation says that when configuring authentication in the app service, we should enable Active Directory and select Express Mode - however, when I do this, there is no such option (see screenshot). Could you perhaps inform me on how to proceed in this case and update the documentation? I suspect it might have something to do with this being Azure Government but honestly I have no idea.

![image](https://user-images.githubusercontent.com/2352828/106346007-78ab7700-6279-11eb-93e6-7463671c5c61.png)

**Comment by ffcruz85** [comment]
So I have managed to get it working by adding Client ID from the AD app registration and Issuer Url from the endpoints in AD overview page, but generally just suggesting that it might be a nice to note in the documentation. This can be closed as far as I am concerned. Thanks again

**Comment by shibayan** [comment]
@ffcruz85 
Thanks for the valuable information, I don't have access to Azure Government, so this kind of feedback is helpful.
I'm going to modify the documentation a bit for environments where Express is not selectable.
