### ISSUE TITLE
The activity function 'Dns01Precondition' failed

### ISSUE THREAD

**Issue by ebowdenqa** [shibayan/appservice-acmebot#283]
**Describe the bug**
The activity function 'Dns01Precondition' failed.  DNS zone(s) are not found. DnsNames = *.dev.myrootdomain.com.

I'm trying to provision a wildcard certificate, but it is also not working when running the Dns01Precondition on a standard domain, such as dev.myrootdomain.com.

**To Reproduce**
1. Within the Azure function, navigate to the function Dns01Precondition
2. Choose Code + Test
3. For the input, enter a domain valid for the web application, such as ['myrootdomain.com']
4. Press Run
5. 2021-02-12T14:36:45.378 [Error] Executed 'Dns01Precondition' (Failed, Id=58c8a8b0-81e6-42dd-aa2f-b6549c4082da, Duration=166ms)DNS zone(s) are not found. DnsNames = myrootdomain.com

The same error occurs if I use the UI found at https://func-myfunctionname-foag.azurewebsites.net/add-certificate

**Environment (please complete the following information):**
 - App Service OS: Windows
 - App Service Type: App Service Plan + Web App
 - Runtime Stack: .Net 4.8
 - Certificate Type: Wildcard.  Though, I have also tried standard certificates

**Additional context**
My app service plan and web app are in resource group A, subscription X.  My DNS zones are in resource group B, subscription Y.  Per the instructions, I assigned the service account for my Azure function as Web Plan Contributor and Web Site Contributor to resource group A.  I assigned the service account for my Azure function as DNS Zone Contributor to resource group B.

I waited over 30 minutes after assigning my service account as DNS Zone Contributor.

Any suggestions or advice for how to debug this?  I suspect my environment having more than one subscription is the difference between my setup and others.

**Comment by shibayan** [comment]
Make sure that Azure DNS is present in the same subscription as Acmebot.
