### ISSUE TITLE
Issuing Certificate for Linux WebApp with external DNS (cloudflare)

### ISSUE THREAD

**Issue by RicardoGaefke** [shibayan/appservice-acmebot#303]
**Describe the bug**
I have a couple of Linux WebApps within CloudFlare DNS. I have a fake Azure DNS zone. When I tried to create a new cert in the past the function app created DNS txt records in my fake DNS and failed. I just copied the txt records to my real CloudFlare DNS and ran the function app again with success.

Now I have a new Linux WebApp and when I try to run the function app I find an error about DNS delegated name server. How can I deal with this new validation?

**To Reproduce**
1. Try to set a certificate for Linux WebAbb with external DNS
2. See error "The delegated name server is not correct"

**Environment (please complete the following information):**
 - App Service OS: Linux
 - App Service Type: Container
 - Runtime Stack: .NET Core (docker images)
 - Certificate Type: Sub-domain

**Additional context**
I've being doing this for a long time (years).

Thanks a lot.

**Comment by RicardoGaefke** [comment]
I just realized as I have external nameservers I won't be able to renew my certs in actual Linux WebApps. Is there a way to rollback and use an old version of this function app or to skip this NS validation in actual version?

Thanks.

**Comment by shibayan** [comment]
This is an extremely irregular method and will remain unavailable in the future.

If you need Cloudflare, you need to use the Key Vault version.
https://github.com/shibayan/keyvault-acmebot
