### ISSUE TITLE
No longer works as it uses a deprecated graph API

### ISSUE THREAD

**Issue by SimonDarksideJ** [shibayan/appservice-acmebot#333]
**Describe the bug**
No longer works as it uses a deprecated graph API

**To Reproduce**
Setup using Azure deploy, and try to configure using the old (classic) settings.
Run app, no resource groups found

**Environment (please complete the following information):**
Azure based on deploy script

**Comment by shibayan** [comment]
Acmebot does not use the Graph API. If it is an error when deploying resources, please share the log.

**Comment by SimonDarksideJ** [comment]
Already switched to the LetsEncrypt extension, so I no longer have access to the error, sorry.
