### ISSUE TITLE
3.4.11 README links to the "latest" ARM template instead of the released revision

### ISSUE THREAD

**Issue by alexey-nikolov-basemark-com** [shibayan/appservice-acmebot#378]
**Describe the bug**
The README.md contains this link:
```
<a href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fshibayan%2Fappservice-acmebot%2Fmaster%2Fazuredeploy.json" target="_blank"><img src="https://aka.ms/deploytoazurebutton" /></a>
```

This is a wrong revision of the ARM template, it should be instead:
```
<a href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fshibayan%2Fappservice-acmebot%2Fv3.4.11%2Fazuredeploy.json" target="_blank"><img src="https://aka.ms/deploytoazurebutton" /></a>
```

**Comment by shibayan** [comment]
In order to eliminate the need for explicit updates and to always provide a version that includes the latest features, only the latest versions of the Deploy to Azure button and application are provided.

**Comment by alexey-nikolov-basemark-com** [comment]
This is basically making any such "releases" nonsensical. Thank you

**Comment by shibayan** [comment]
If we lived in a world where all users watched GitHub releases and updated them properly, I would have done what you said.
