### ISSUE TITLE
Acmebot and Private Azure DNS 

### ISSUE THREAD

**Issue by Charrany** [shibayan/appservice-acmebot#404]
I'm deploying a private PKI in an azure environment and I'm using smallstep opensource product as a private CA along side with Acmebot to automate the issuance and renewal of ACME SSL/TLS certificates.

But when i tried to test the issuance of certificate i was unable to select a private DNS zone which had lead me to this question:
**Is Acmebot compatible with Private DNS zones?**

**We want to use http01 ACME challenge.**

Another question:
Can I choose the type of the ACME challenge that should be accomplished by the client to have the certificate?

**Comment by shibayan** [comment]
The App Service version supports http-01 challenge.
