### ISSUE TITLE
avoid adding/cleaning .well-known virtual path if it exists

### ISSUE THREAD

**Issue by dhvik** [shibayan/appservice-acmebot#418]
When issuing or renewing a certificate the virtual path .well-known is created and removed. 
This causes the application to restart and if you have a large application with a long startup time the downtime causes more problems than necessary.

I would suggest that you could prepare the .well-known virtual path in beforehand so it don't need to be created or removed to avoid disruptions in the web service.

**Comment by shibayan** [comment]
See #110 for the history of this behavior. A method using DNS authentication is also available.
