### ISSUE TITLE
Troubleshooting: "Failed to access SCM site. Message: Response status code does not indicate success: 401 (Unauthorized)"

### ISSUE THREAD

**Issue by marthijn** [shibayan/appservice-acmebot#440]
I have a suggestion for the troubleshooting section in the wiki. To assign certificates to a web app it is required to have the setting "Basic Auth Publishing Credentials" (in General settings) set to "On". Otherwise you will see an error message like:
```
Exception while executing function: IssueCertificate Orchestrator function 'IssueCertificate' failed: The activity function 'Http01Precondition' failed: "Failed to access SCM site. Message: Response status code does not indicate success: 401 (Unauthorized).". See the function execution logs for additional details. 
```

**Comment by shibayan** [comment]
We have changed Acmebot to use Bearer Token authentication instead of Basic authentication for execution, so the latest version will work correctly even if Basic authentication is disabled.
