### ISSUE TITLE
Support for .NET 6 ends on 12 November 2024

### ISSUE THREAD

**Issue by Tom-RedCactus** [shibayan/appservice-acmebot#450]
Received the following email from Microsoft:
Support for .NET 6 ends on 12 November 2024 upgrade your Azure Functions apps to .NET 8

Is it possible to update the function app to .NET 8?

**Comment by shibayan** [comment]
There are of course plans to update to .NET 8. However, we are still waiting as Microsoft has not yet released the necessary updates to support it.

**Comment by Tom-RedCactus** [comment]
Thank you for the update. We'll patiently await Microsoft's update

**Comment by marthijn** [comment]
@shibayan Eventually the functions should be migrated to isolated-mode right?

**Comment by shibayan** [comment]
@marthijn Starting with .NET 10, only Isolated will be supported, so we are considering migrating at that time. We would like to remain In-Process during .NET 8.

**Comment by Skoucail** [comment]
@shibayan Any update? As nov 12 is coming very soon.
