### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by flacidsnake** [shibayan/appservice-acmebot#452]
**Describe the bug**
When I access the "add-certificate" function, I get "Error 502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server."

**To Reproduce**
1. Go to [your function](https://yourfunction-letsencrypt-wgac.azurewebsites.net/add-certificate)
2. See error `502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server`

**Environment (please complete the following information):**
 - App Service OS: Windows
 - App Service Type: Package Type
 - Runtime Stack: [e.g. .NET v4.7, PHP, Node.js]
 - Certificate Type: Sub-domain

**Additional context**
Last time the certificates were automatically renewed was 22.01.2024.

Thanks in advance

**Comment by shibayan** [comment]
Are you seeing any error logs in Application Insights being deployed at the same time? 502 errors can also be caused by Azure issues.

**Comment by flacidsnake** [comment]
Thank you for your answer!
The Azure Function was using runtime version 3, which is deprecated. I just redeployed everything again and now it's on version 4, so I guess I can close this.

Thanks again for your dedication and support :)

**Comment by marthijn** [comment]
@shibayan Same problem here. The function cannot start/restart: `Encountered an error (InternalServerError) from host runtime.`

How do I redeploy everything without breaking stuff? Is that simply removing the resource group and it's resources, and restart the deployment process from the deploy link in the readme? (by the way, I thought the app was auto updating?)

**Comment by leppie** [comment]
@marthijn had the same issue. 

Easiest is to just deploy a fresh one, then just copy and adjust configuration of the original app and restart. Then delete fresh one.
