### ISSUE TITLE
Documentation - Feedback

### ISSUE THREAD

**Issue by VaclavElias** [shibayan/appservice-acmebot#70]
Hi, 

Thank you for this application. I have just tested it and put together for you some comments which if I knew before would speed up significantly my usage of this project, at least for me, hope also for others. It is just more explanatory wordings.

I found it quite confusing for myself. While your steps might be very clear for an experienced Azure users, a few more comments would help less experienced Azure users.

_My reasoning in Italic._

0. In your description you could mention also:
- This is an alternative solution to https://github.com/sjkp/letsencrypt-siteextension 
_(this is not to promote the other option but I didn't know clearly if this project solves the same problem, installing Let's Encrypt certificate for Azure Web App. This would make it very clear to me that I am in the right place as I think there are only 2 options how to do it, through this project and the alternative)_
- This project creates/deploys one Azure App Service (Consumption Plan) you name in the deployment process with one Azure Service and a few Azure Functions in it. 
_(this would explain clearly how your project is going to work)_

_This would make very clear that this project is trying to achieve the same as an alternative solution but more efficient way._

1. Deployment to Azure Functions (_please elaborate more what that means, I saw there two icons and have no idea what it is going to do._)
- When you click "Deploy to Azure", your Azure portal will open and a few resources (listed below) will be added to your subscription once you approved it. 
_(maybe put in the table what resources, description and reason. I was personally very confused and worried what this is doing and why as it says Purchase when you confirm this)_

_Also, naming the app service is quite important as my deployment failed, see below._

_The first mistake I made was to name my App Service **letsencrypt**.  Well, all resources were created except one._

- Maybe mention to prefix or suffix app name to avoid failed deployment.

```
Conflict
STATUS MESSAGE { "Code": "Conflict", "Message": "Website with given name letsencrypt already exists.", "Target": null, "Details": [ { "Message": "Website with given name letsencrypt already exists." }, { "Code": "Conflict" }, { "ErrorEntity": { "ExtendedCode": "54001", "MessageTemplate": "Website with given name {0} already exists.", "Parameters": [ "letsencrypt" ], "Code": "Conflict", "Message": "Website with given name letsencrypt already exists." } } ], "Innererror": null }
PROVISIONING STATE Failed
TIMESTAMP 24/04/2019, 16:20:18
DURATION 4 seconds
TYPE Microsoft.Web/sites
RESOURCE ID /subscriptions/08819ce4-9304-443b-bba6-f72ba92f9912/resourceGroups/UkResourceGroup/providers/Microsoft.Web/sites/letsencrypt
RESOURCE letsencrypt
```

2. Add application settings key.
- These keys should be created automatically but you can double check that they are in your new created function under "Application Settings"

3.  Enable App Service Authentication (EasyAuth) with AAD
- In the new created Function, open Platform Features -> Authentication / Authorization  ...

4. Assign roles to target resource group _(Here I got lost, where can I get that window Add permissions?)_
- Select Resource Group (where you Azure Service is installed) -> Access Control (IAM) -> Add -> Add Role Assignment
- You need to click Role Assignments to see the roles were added

Usage - Adding new certificate - When/Why should I tick "Use IP Based SSL"?

Well, at this point all was deployed and working.

Thank you everyone :)

**Comment by shibayan** [comment]
@VaclavElias Thank you for feedback!
I will continue to improve the documentation and deployment.

**Comment by VaclavElias** [comment]
You are welcome and thank you!

**Comment by VaclavElias** [comment]
This could also be added.

> It is necessary to check RenewCertificates and AddCertificate for health check.
