### ISSUE TITLE
Suggestion: Create wildcard certs and bind them to domains.

### ISSUE THREAD

**Issue by VALLIS-NERIA** [shibayan/appservice-acmebot#95]
This app is fantastic but I'm giving a small suggestion. If I want to create a wildcard cert, for example, *.dummy.com, I have to add *.dummy.com as a custom domain of my site. However I do not wish others can access my site via abc.dummy.com or mail.dummy.com. The site should only be available at dummy.com and www.dummy.com.

Another case is that I have multiple web apps. e.g., a function app binded to api.dummy.com and a website binded to www.dummy.com. I wish these domains can share a same wildcard cert issued to *.dummy.com.

Would it be possible that the app creates cert for *.dummy.com and automatically bind the cert to any sub-domains? I think I'm able to implement this feature but things will go much more easier if you could help. Thanks.

**Comment by shibayan** [comment]
If you want to apply multiple wildcard certificates, please consider using this.
https://github.com/shibayan/keyvault-acmebot

It is separated from App Service and can be handled flexibly as a Key Vault Certificate.

**Comment by bbakermmc** [comment]
@VALLIS-NERIA @shibayan Not sure if this is the same question or not.
But lets say I want to create a SAN cert for: *.site.com, *.dev.site.com, *.stage.site.com, and then I want to have it bound to multiple slots/sites, what tool do I use lol?
Ideally would be nice to have 1 page where we can say I want a cert for xxx domains and I want the bindings made and the cert applied to xxx apps/slots.

**Comment by shibayan** [comment]
Basically, you should only use this app if you are issuing certificates to a domain that is bound to a simple App Service.

If you issue a SANs certificate and bind to multiple App Services, you must use the Key Vault version.

**Comment by VALLIS-NERIA** [comment]
@bbakermmc that's exactly what I'm working on. Take a look at my fork on branch dev3, this feature is basicly useable but the code is rather rough so it's not ready for a PR

**Comment by bbakermmc** [comment]
@VALLIS-NERIA Sounds good, let me know if you want me to test when you have a version ready.
