### ISSUE TITLE
Function breaks IdentityServer discovery endpoint

### ISSUE THREAD

**Issue by jnsn** [shibayan/appservice-acmebot#98]
I discovered an issue when using this extension on a website which uses [IdentityServer4](http://docs.identityserver.io/en/latest/index.html).

IdentityServer has a [discovery endpoint](http://docs.identityserver.io/en/latest/endpoints/discovery.html) which can be used to retrieve metadata about your IdentityServer - it returns information like the issuer name, key material, supported scopes etc. The discovery endpoint is available via `/.well-known/openid-configuration` relative to the base address.

This conflicts when using this plugin, because the `.well-known` folder is mapped to folder under the site root, and not the `wwwroot` folder in the web app folder.

I know that IdentityServer is capable of working if a `.well-known` folder exists in it's base directory, so I was wondering if the function will still work if I move the folder and remove the virtual path mapping? Will it still be able to automatically renew the certificate, or are there any absolute or relative paths used within the function which expect the files to be exactly where they are?

**Comment by shibayan** [comment]
The `.well-known` directory was not considered for use elsewhere. Perhaps it is very difficult to solve this problem. It is also a specification of IIS.

If I add the option to use Azure DNS, You will be able to issue certificates without using the `.well-known` directory.
